[run]
concurrency = 8
deadline = "2m"
tests = false
skip-dirs = ["vendor"]
skip-files = ["main.go"]

[output]
format = "colored-line-number"

[linters]
enable-all = true
disable = ["gochecknoglobals", "exhaustivestruct", "goerr113"]
