---

run:
  concurrency: 4
  deadline: 1m
  tests: true
  issues-exit-code: 1
  skip-dirs:
    - vendor$

linters:
  enable-all: true
  disable:
    - lll
    - gochecknoglobals
  disable-all: false
  fast: false
