---

language: go
sudo: false
dist: trusty

go:
  - "1.11.x"
  - master

before_script: make prepare

script:
  - make all
  - make lint
  - make citest

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: master
